import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h4 className="title">
				<i class="fa-solid fa-face-smile"></i> Ana Sayfa
			</h4>
			<style jsx>{`
				.title {
					color: green;
				}
			`}</style>
		</>
	);
}
